sudo: false
language: java
jdk:
  - oraclejdk8

deploy:
  provider: releases
  api_key:
    secure: "JTHyvjoLVigoZPAtbAODCtEY0Wv9XyIAnOnQfjF3EbfkYp9NMSn1Q/ZEQECodyYLFgmoUlYsuOVs2yfW9qnTo4/vvcSbJgxg182H4I9MRQCgxLkVeh/utYcTIcKgdj42vjG6I/aEbPoO4KqSTcrE+zsa5OyHL7x42Ohoy+qLzzbw08WywrfdLLgGuI1dZYNkgMVjtcJ5MBhchTvWvDlF73fzrtcWYVphiv7g0JoYs5xRlTA29JLWwD2YCB4g61sVRIzBbr7Rs8XilmFyN4Rboql9pIPMKlaDZGMzrXjt1WocF4z/qTiKUvWFtBlNu4AdCwOEeKFLsrbz9hzvk27dUmd1HDouCkDA2wTh1UYasYgmoCxyTzTnmKp0yZvCx4zhoyPISHYK6QnnRaohkLonHQvPy3R9mRcbox+cWOlniAQLkj5jk2JLhiWYAmnAGhvsxnSckc+VIw3eK9pCPH6zuDV/KktEU6/ozO+iB5mslalyGCRwNy2CFkdYQnkduVwohAkKRNivwYHDaLVshdzo4xoQa8yp1KX6UPJ8R55uKAaTICtZc/bVtSiTQ3Lg7y5iCwPvsSJAHfIYXPuzg9noYc1PNqt77BzmkJoav4RlTY1/2iJMMfzK9BneSSB3wpV9/CXUVA/UPZY45tup2S619tij6KbDHsIK84cr95UL0f4"
  file: ./target/dbmole-final.jar
  skip_cleanup: true
  draft: true
  on:
    tags: true